# Generated by Django 2.2 on 2022-08-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogin', '0004_auto_20220827_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
    ]
